foreground            #c5bda3
background            #181b1f
selection_foreground  #181b1f
selection_background  #c5bda3

url_color #73a9a2

# black
color0  #272e33
color8  #414b50

# red
color1  #d77072
color9  #d77072

# green
color2  #98a561
color10 #98a561

# yellow
color3  #ccad74
color11 #ccad74

# blue
color4  #73a9a2
color12 #73a9a2

# magenta
color5  #c78ca7
color13 #c78ca7

# cyan
color6  #77af85
color14 #77af85

# white
color7  #c5bda3
color15 #d8cfb3

# Cursor colors
cursor            #c5bda3
cursor_text_color background

# Tab bar colors
active_tab_foreground   #181b1f
active_tab_background   #c5bda3
inactive_tab_foreground #c5bda3
inactive_tab_background #272e33

# Marks
mark1_foreground #181b1f
mark1_background #d77072

# Splits/Windows
active_border_color #98a561
inactive_border_color #272e33
